# Generated by Django 3.2.1 on 2021-05-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Info_objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Object_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='incident_type_OLEG1',
            new_name='Incident_type_OLEG1',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='level_detection',
            new_name='Level_detection',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='premed_fact',
            new_name='Premed_fact',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='unauth_behavior',
            new_name='Unauth_behavior',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='information_asset',
        ),
        migrations.AddField(
            model_name='incident',
            name='Information_asset',
            field=models.ManyToManyField(to='incidents.Info_assets'),
        ),
    ]
