# Generated by Django 3.2.1 on 2021-05-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_auto_20210507_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='Incident_type_OLEG1',
        ),
        migrations.AddField(
            model_name='incident',
            name='BankTechProcc',
            field=models.CharField(choices=[('PAYT', 'Платежные технологические процессы'), ('INFO', 'Информационные технологические процессы')], default='Нет', max_length=4),
        ),
        migrations.AddField(
            model_name='incident',
            name='Consequences',
            field=models.CharField(choices=[('MIN', 'Минимальный'), ('MAX', 'Средняя'), ('MID', 'Высокая'), ('CRIT', 'Критическая')], default='Нет', max_length=4),
        ),
        migrations.AddField(
            model_name='incident',
            name='Incident_priority',
            field=models.CharField(choices=[('0', 'Наивысший'), ('1', 'Высокий'), ('2', 'Повышенный'), ('3', 'Средний'), ('4', 'Низкий'), ('5', 'Минимальный')], default='5', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='Incident_urgency',
            field=models.CharField(choices=[('COMM', 'Обычная'), ('HIGH', 'Высокая')], default='COMM', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='Information_object',
            field=models.ManyToManyField(to='incidents.Info_objects'),
        ),
        migrations.AddField(
            model_name='incident',
            name='Level_incident',
            field=models.CharField(choices=[('PHIS', 'Физический'), ('NETW', 'Сетевой'), ('OS', 'Операционных систем'), ('BD', 'Систем управления базами данных'), ('BTEC', 'Банковских технологических процессов и приложений'), ('BPRC', 'Бизнес-процессов организации')], default='OS', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='Range',
            field=models.CharField(choices=[('MIN', 'Пределы одной АБС'), ('MAX', 'Пределы отдельного структурного подразделения организации БС РФ'), ('MID', 'Организации БС РФ в целом'), ('CRIT', 'Выходящий за пределы организации БС РФ')], default='MIN', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='Recurrence_possibility',
            field=models.CharField(choices=[('MIN', 'Минимальный'), ('MAX', 'Средняя'), ('MID', 'Высокая'), ('CRIT', 'Критическая')], default='Нет', max_length=4),
        ),
    ]
