# Generated by Django 3.2.1 on 2021-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_auto_20210507_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='Closed_date',
            field=models.DateField(default='2021-05-21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='Consequences_org',
            field=models.TextField(default='Нет'),
        ),
        migrations.AddField(
            model_name='incident',
            name='Departments_alerts',
            field=models.ManyToManyField(to='incidents.Department'),
        ),
        migrations.AddField(
            model_name='incident',
            name='Functional_group',
            field=models.CharField(default='Нет', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='Functional_group_time',
            field=models.CharField(default='Нет', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='Incident_closure_level',
            field=models.CharField(choices=[('COMM', 'Обычная'), ('HIGH', 'Высокая')], default='COMM', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='Incident_elimination_report',
            field=models.CharField(default='Нет', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='Incident_escalation',
            field=models.CharField(choices=[('YES', 'Да'), ('NO', 'Нет')], default='NO', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='Incident_report',
            field=models.CharField(default='Нет', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='Incident_status',
            field=models.CharField(choices=[('REGI', 'Зарегистрирован'), ('ASSG', 'Назначен'), ('WORK', 'В работе'), ('CLSD', 'Закрыт')], default='WORK', max_length=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GRIIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialists_FIO', models.ManyToManyField(to='incidents.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='Scpec_assigment',
            field=models.ManyToManyField(default='Нет', to='incidents.GRIIB'),
        ),
    ]
