# Generated by Django 3.2.1 on 2021-05-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_auto_20210507_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='Departments_alerts',
            field=models.ManyToManyField(default='Нет', to='incidents.Department'),
        ),
    ]
