# Generated by Django 3.2.1 on 2021-05-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_alter_incident_departments_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='Tch',
            field=models.CharField(default='Нет', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='Departments_alerts',
            field=models.ManyToManyField(blank=True, to='incidents.Department'),
        ),
    ]
